package com.believeyourself.leetcode.findtheDifference;

/**
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindtheDifference {

    /**
     * 利用字典表
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference(String s, String t) {
        int[] sTable = new int[26];
        int[] tTable = new int[26];
        for(char c : s.toCharArray()){
            sTable[c - 'a']++;
        }
        for(char c : t.toCharArray()){
            tTable[c - 'a']++;
        }
        for(int i = 0; i < 26; i++){
            if(sTable[i] != tTable[i]){
                return (char) ('a' + i);
            }
        }
        return 'a';
    }
}
